services:
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000" # Expose Nuxt app on port 3000
    depends_on:
      - db # Ensure the database service starts first

  # backend:
  #   build: ./backend
  #   depends_on:
  #     - db
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #     POSTGRES_HOST: db
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./backend:/app
  #   command: yarn start

volumes:
  db_data: