services:
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/app
    ports:
      - "3000:3000" 
    depends_on:
      - db 


volumes:
  db_data: